/**
 * TKT-071: Information Architecture (IA) Generation Prompt
 *
 * Phase 1 of IA-first greenfield architecture.
 * This prompt focuses ONLY on generating site structure with page purposes.
 * NO component schemas - those come in Phase 2.
 */

export interface IAMetadata {
  purpose: string
  targetAudience: string
  primaryQuestion: string
  journeyStage: 'awareness' | 'interest' | 'consideration' | 'decision'
  /** High-level descriptions of what each section should accomplish (NOT component types) */
  sectionIntents: string[]
}

export interface IAPage {
  slug: string
  title: string
  parentSlug: string | null
  iaMetadata: IAMetadata
}

export interface BusinessInfo {
  websiteName: string
  description: string
  targetAudience: string
  suggestedFeatures: string[]
  originalPrompt: string
}

/**
 * Builds the system prompt for Phase 1: Information Architecture generation.
 * The AI should call createSiteStructure with a complete page hierarchy.
 */
export function buildIAGenerationPrompt(businessInfo: BusinessInfo): string {
  const segments: string[] = []

  // Goal
  segments.push('# Phase 1: Information Architecture Generation')
  segments.push('')
  segments.push('Your task is to design the SITE STRUCTURE only.')
  segments.push('Do NOT generate content or components - that happens in Phase 2.')
  segments.push('')

  // PRD Detection and Following (CRITICAL - HIGHEST PRIORITY)
  segments.push('## PRD/Specification Detection (HIGHEST PRIORITY)')
  segments.push('')
  segments.push('If the user input contains a PRD (Product Requirements Document) or specification:')
  segments.push('')
  segments.push('**1. FOLLOW THE SITEMAP EXACTLY**')
  segments.push('Look for sections like "## Sitemap", "### Site Structure", or similar.')
  segments.push('Create ONLY the pages specified in the sitemap - no more, no less.')
  segments.push('')
  segments.push('**2. RESPECT "CUT" OR "NOT IN MVP" MARKERS**')
  segments.push('If pages are marked as:')
  segments.push('  - ~~strikethrough~~')
  segments.push('  - "CUT from MVP"')
  segments.push('  - "NOT in MVP"')
  segments.push('  - "Post-launch" or "Week 2+"')
  segments.push('DO NOT create those pages. They were explicitly excluded.')
  segments.push('')
  segments.push('**3. EXTRACT ALL SECTION REQUIREMENTS FROM PAGE SPECS (CRITICAL)**')
  segments.push('Look for "### Section X:" or "### Page Specification" headers.')
  segments.push('**EVERY numbered section MUST be included in sectionIntents.**')
  segments.push('')
  segments.push('Example PRD section headers:')
  segments.push('```')
  segments.push('### Section 1: Hero')
  segments.push('### Section 2: Services')
  segments.push('### Section 3: Why Choose Us')
  segments.push('### Section 4: Contact / CTA')
  segments.push('### Section 5: Footer')
  segments.push('```')
  segments.push('')
  segments.push('For this PRD, sectionIntents MUST describe ALL 5 sections:')
  segments.push('["Hero with headline and CTA", "Services overview grid", "Why choose us benefits", "Contact call-to-action", "Footer with links"]')
  segments.push('')
  segments.push('**DO NOT stop at the first few sections - extract EVERY "### Section X:" entry!**')
  segments.push('')
  segments.push('**SPLIT COMPOUND SECTIONS INTO MULTIPLE ENTRIES:**')
  segments.push('Some PRD sections contain MULTIPLE component types. Split them:')
  segments.push('')
  segments.push('Example: "Social Proof" section with BOTH stats AND testimonials:')
  segments.push('```')
  segments.push('### Section 5: Social Proof')
  segments.push('- Stats: 25,000+ customers, 4.8/5 rating')
  segments.push('- Reviews: [3 customer quotes]')
  segments.push('```')
  segments.push('→ sectionIntents: ["Statistics showing key metrics (25K+ customers, 4.8 rating)", "Customer testimonials with 3 quotes"]  // TWO entries!')
  segments.push('')
  segments.push('Example: "Hero + Newsletter" section with BOTH elements:')
  segments.push('```')
  segments.push('### Section 7: Newsletter')
  segments.push('- Headline: "Join Us"')
  segments.push('- Email input field')
  segments.push('```')
  segments.push('→ Since newsletter uses footer.newsletter field, include it in footer spec')
  segments.push('')
  segments.push('**4. HOME PAGE IS ALWAYS REQUIRED**')
  segments.push('Every website needs a home page with slug "home".')
  segments.push('Extract home page sections from the PRD\'s home page specification.')
  segments.push('')
  segments.push('**Example PRD Sitemap:**')
  segments.push('```')
  segments.push('## Sitemap')
  segments.push('├── / (Home)')
  segments.push('│   └── Hero + Value Props + Proof + CTA')
  segments.push('└── /contact (Optional)')
  segments.push('')
  segments.push('CUT from MVP:')
  segments.push('- ~~/product~~')
  segments.push('- ~~/pricing~~')
  segments.push('```')
  segments.push('')
  segments.push('**For this PRD, you would create:**')
  segments.push('- ✅ home page with sectionIntents describing: hero, value props, proof, CTA, footer')
  segments.push('- ✅ contact page (optional but mentioned)')
  segments.push('- ❌ DO NOT create product page (explicitly CUT)')
  segments.push('- ❌ DO NOT create pricing page (explicitly CUT)')
  segments.push('')

  // Business context
  segments.push('## Business Context')
  segments.push(`Website Name: ${businessInfo.websiteName}`)
  segments.push(`Description: ${businessInfo.description}`)
  segments.push(`Target Audience: ${businessInfo.targetAudience}`)
  if (businessInfo.suggestedFeatures.length > 0) {
    segments.push(`Suggested Features: ${businessInfo.suggestedFeatures.join(', ')}`)
  }
  segments.push('')
  segments.push('Original User Request:')
  segments.push(businessInfo.originalPrompt)
  segments.push('')

  // IA metadata schema
  segments.push('## IA Metadata Schema')
  segments.push('Each page MUST have an iaMetadata object with these fields:')
  segments.push('')
  segments.push('```typescript')
  segments.push('interface IAMetadata {')
  segments.push('  purpose: string        // What this page accomplishes for the visitor')
  segments.push('  targetAudience: string // Who this page is specifically for')
  segments.push('  primaryQuestion: string // The main question this page answers')
  segments.push('  journeyStage: "awareness" | "interest" | "consideration" | "decision"')
  segments.push('  sectionIntents: string[] // High-level DESCRIPTIONS of what each section should accomplish')
  segments.push('}')
  segments.push('```')
  segments.push('')
  segments.push('**IMPORTANT: sectionIntents are DESCRIPTIONS, not component types!**')
  segments.push('')
  segments.push('✅ CORRECT sectionIntents (describe the PURPOSE):')
  segments.push('- "Hero section with headline, value proposition, and main CTA button"')
  segments.push('- "Services overview showing 6 key offerings with icons and descriptions"')
  segments.push('- "Customer testimonials with 3-4 quotes from satisfied clients"')
  segments.push('- "Final call-to-action encouraging visitors to book a consultation"')
  segments.push('- "Footer with contact info, links, and newsletter signup"')
  segments.push('')
  segments.push('❌ WRONG (do NOT use component type names):')
  segments.push('- "hero-simple" ← This is a component type, not a description')
  segments.push('- "feature-grid" ← This is a component type, not a description')
  segments.push('- "cta-banner" ← This is a component type, not a description')
  segments.push('')

  // Journey stage mapping
  segments.push('## Journey Stage Mapping')
  segments.push('')
  segments.push('Map each page to the appropriate buyer journey stage:')
  segments.push('')
  segments.push('| Stage | Purpose | Example Pages |')
  segments.push('|-------|---------|---------------|')
  segments.push('| awareness | Introduce problem/solution | Home, Blog posts |')
  segments.push('| interest | Build curiosity, show value | About, Services overview |')
  segments.push('| consideration | Compare options, prove credibility | Portfolio, Case studies, Testimonials |')
  segments.push('| decision | Convert visitor to action | Contact, Pricing, Get Started |')
  segments.push('')

  // Page hierarchy rules
  segments.push('## Page Hierarchy Rules')
  segments.push('')
  segments.push('1. Home is the ROOT (parentSlug: null)')
  segments.push('2. All other pages are children of Home (parentSlug: "home")')
  segments.push('')
  segments.push('**SINGLE-PAGE DETECTION (CRITICAL - CHECK FIRST):**')
  segments.push('If the sitemap shows:')
  segments.push('  - "Single page website"')
  segments.push('  - "├── / (Home)" with NO other pages listed')
  segments.push('  - Only one entry in the sitemap')
  segments.push('')
  segments.push('Then CREATE ONLY THE HOME PAGE. Do NOT add About, Services, or Contact pages.')
  segments.push('Put ALL sections from the PRD on the home page\'s sectionIntents array.')
  segments.push('')
  segments.push('3. For MULTI-PAGE websites (sitemap shows multiple pages):')
  segments.push('   Standard structure:')
  segments.push('   - Home: First impression, hook visitors')
  segments.push('   - About: Build trust, tell the story')
  segments.push('   - Services/Portfolio: Show what you offer/have done')
  segments.push('   - Contact: Convert to action')
  segments.push('')
  segments.push('4. Use SIMPLE page names: "About", "Services", "Contact"')
  segments.push('   NOT verbose: "About the Company", "Our Services Page"')
  segments.push('')

  // Nested page rules (CRITICAL for avoiding validation errors)
  segments.push('## Nested Page Rules (CRITICAL)')
  segments.push('')
  segments.push('If creating nested pages (children of non-home pages):')
  segments.push('1. ALWAYS include the parent page BEFORE its children')
  segments.push('2. The parent page MUST exist in your pages array')
  segments.push('')
  segments.push('Example - CORRECT nested structure:')
  segments.push('```json')
  segments.push('[')
  segments.push('  { "slug": "home", "parentSlug": null },')
  segments.push('  { "slug": "portfolio", "parentSlug": "home" },')
  segments.push('  { "slug": "commissions", "parentSlug": "portfolio" },')
  segments.push('  { "slug": "shoots", "parentSlug": "portfolio" }')
  segments.push(']')
  segments.push('```')
  segments.push('')
  segments.push('Example - WRONG (will fail validation):')
  segments.push('```json')
  segments.push('[')
  segments.push('  { "slug": "home", "parentSlug": null },')
  segments.push('  { "slug": "commissions", "parentSlug": "portfolio" },')
  segments.push('  { "slug": "shoots", "parentSlug": "portfolio" }')
  segments.push(']')
  segments.push('```')
  segments.push('This fails because "portfolio" page does not exist in the array!')
  segments.push('')

  // Section intents guidance
  segments.push('## Section Intents Guidance')
  segments.push('')
  segments.push('For each page, describe what sections are needed using plain language.')
  segments.push('Phase 2 will decide which components to use based on these intents.')
  segments.push('')
  segments.push('**Good section intents describe WHAT the section should accomplish:**')
  segments.push('- "Hero section introducing the business with headline and primary call-to-action"')
  segments.push('- "Grid of 6 services with icons, titles, and short descriptions"')
  segments.push('- "Team section showing 4 team members with photos and bios"')
  segments.push('- "Customer testimonials carousel with 3-4 quotes"')
  segments.push('- "Pricing comparison table with 3 tiers"')
  segments.push('- "Contact form with name, email, and message fields"')
  segments.push('- "FAQ section with expandable questions and answers"')
  segments.push('- "Photo gallery showcasing 8-12 portfolio images"')
  segments.push('- "Statistics section showing 4 key metrics"')
  segments.push('- "Final call-to-action banner encouraging sign-ups"')
  segments.push('- "Footer with navigation links, contact info, and social media"')
  segments.push('')
  segments.push('**Every page should include intents for:**')
  segments.push('- A navigation/header section (first)')
  segments.push('- Content sections specific to the page purpose')
  segments.push('- A footer section (last)')
  segments.push('')

  // Output format
  segments.push('## Output')
  segments.push('')
  segments.push('Call the createSiteStructure tool with this structure:')
  segments.push('')
  segments.push('```json')
  segments.push('{')
  segments.push('  "websiteId": "<provided>",')
  segments.push('  "pages": [')
  segments.push('    {')
  segments.push('      "slug": "home",')
  segments.push('      "title": "Home",')
  segments.push('      "parentSlug": null,')
  segments.push('      "iaMetadata": {')
  segments.push('        "purpose": "Hook visitors, introduce the business value proposition",')
  segments.push('        "targetAudience": "First-time visitors exploring options",')
  segments.push('        "primaryQuestion": "What does this business do and why should I care?",')
  segments.push('        "journeyStage": "awareness",')
  segments.push('        "sectionIntents": [')
  segments.push('          "Navigation bar with logo and links to all pages",')
  segments.push('          "Hero section with headline, tagline, and primary CTA button",')
  segments.push('          "Services grid showing 4-6 key offerings with icons",')
  segments.push('          "Customer testimonials with 3 quotes from satisfied clients",')
  segments.push('          "Final call-to-action encouraging visitors to get started",')
  segments.push('          "Footer with contact info, social links, and copyright"')
  segments.push('        ]')
  segments.push('      }')
  segments.push('    },')
  segments.push('    {')
  segments.push('      "slug": "about",')
  segments.push('      "title": "About",')
  segments.push('      "parentSlug": "home",')
  segments.push('      "iaMetadata": {')
  segments.push('        "purpose": "Build trust by sharing the story and values",')
  segments.push('        "targetAudience": "Visitors wanting to know who they are working with",')
  segments.push('        "primaryQuestion": "Who are these people and can I trust them?",')
  segments.push('        "journeyStage": "interest",')
  segments.push('        "sectionIntents": [')
  segments.push('          "Navigation bar with logo and links",')
  segments.push('          "Company story and mission statement",')
  segments.push('          "Team members grid with photos and bios",')
  segments.push('          "Footer with contact info and links"')
  segments.push('        ]')
  segments.push('      }')
  segments.push('    }')
  segments.push('  ]')
  segments.push('}')
  segments.push('```')
  segments.push('')

  // Critical rules
  segments.push('## Critical Rules')
  segments.push('')
  segments.push('- Generate ONLY site structure, NOT content')
  segments.push('- Each page MUST have complete iaMetadata')
  segments.push('- Keep to 4 pages unless business clearly needs more')
  segments.push('- Map journey stages thoughtfully based on page purpose')
  segments.push('- sectionIntents should be descriptive (what the section does), NOT component type names')
  segments.push('')

  // Section count validation (CRITICAL)
  segments.push('## SECTION COUNT VALIDATION (CRITICAL)')
  segments.push('')
  segments.push('Before outputting, COUNT the sections in the PRD:')
  segments.push('')
  segments.push('1. Look for all "### Section X:" headers in the PRD')
  segments.push('2. Count them (e.g., Section 1, Section 2, Section 3, Section 4, Section 5 = 5 sections)')
  segments.push('3. Your sectionIntents array MUST have AT LEAST that many entries')
  segments.push('4. Include navbar and footer intents too')
  segments.push('')
  segments.push('**Example validation:**')
  segments.push('PRD has: Hero, About, Menu, Visit Us, Footer = 5 sections')
  segments.push('Your sectionIntents should describe all 5+ intents')
  segments.push('')
  segments.push('**If you only output 2-3 intents when the PRD has 5+, YOU ARE WRONG. Go back and read ALL sections.**')
  segments.push('')

  // CRITICAL: Don't Invent Constraints
  segments.push('## CRITICAL: Do NOT Invent Content')
  segments.push('')
  segments.push('When the user provides a PRD/specification:')
  segments.push('')
  segments.push('1. **ONLY create sections listed in the PRD** - do NOT add extra sections')
  segments.push('2. **Do NOT add testimonials** unless the PRD explicitly requests them')
  segments.push('3. **Do NOT add case studies** unless the PRD explicitly provides them')
  segments.push('4. **Do NOT invent founder credentials, team bios, or company history**')
  segments.push('5. **Do NOT add social proof sections** (testimonials, reviews, logos) unless PRD specifies')
  segments.push('6. **Use ONLY the page structure from the PRD sitemap** - no extras')
  segments.push('')
  segments.push('If the PRD says:')
  segments.push('```')
  segments.push('Home page sections: Hero, Value Props, CTA')
  segments.push('```')
  segments.push('')
  segments.push('Then create sectionIntents for EXACTLY those sections (plus navbar/footer).')
  segments.push('Do NOT add extra sections unless PRD specifies them.')
  segments.push('')

  // Anti-pattern rules (CRITICAL)
  segments.push('## ANTI-PATTERNS - NEVER DO THESE')
  segments.push('')
  segments.push('**NEVER create these as page slugs** (they are COMPONENTS, not pages):')
  segments.push('- ❌ "navbar", "nav", "navigation", "header", "top-nav"')
  segments.push('- ❌ "footer", "bottom-nav", "site-footer"')
  segments.push('- ❌ "sidebar", "menu", "main-menu"')
  segments.push('')
  segments.push('These are UI COMPONENTS that go INSIDE pages, not pages themselves.')
  segments.push('If the user mentions navbar/footer requirements, those describe components')
  segments.push('that should appear ON every page, not as separate pages.')
  segments.push('')
  segments.push('**ALWAYS create at minimum:**')
  segments.push('- ✅ "home" page (slug: "home") - Every website needs a homepage')
  segments.push('')
  segments.push('**For SINGLE-PAGE websites (sitemap shows only Home):**')
  segments.push('- ✅ Create ONLY the home page')
  segments.push('- ✅ Put ALL sections in home page\'s sectionIntents')
  segments.push('- ❌ Do NOT add extra pages (about, contact, etc.)')
  segments.push('')
  segments.push('**For MULTI-PAGE websites (sitemap shows multiple pages):**')
  segments.push('- ✅ Create all pages listed in the sitemap')
  segments.push('')
  segments.push('**Example of WRONG structure:**')
  segments.push('```json')
  segments.push('{ "pages": [{ "slug": "navbar" }, { "slug": "footer" }] }  // WRONG!')
  segments.push('```')
  segments.push('')
  segments.push('**Example of CORRECT structure:**')
  segments.push('```json')
  segments.push('{ "pages": [{ "slug": "home" }, { "slug": "about" }, { "slug": "contact" }] }  // CORRECT!')
  segments.push('```')

  return segments.join('\n')
}
