/**
 * TKT-071: Per-Page Content Generation Prompt
 *
 * Phase 2 of IA-first greenfield architecture.
 * This prompt generates content for ONE page at a time, with full IA context.
 */

import type { IAMetadata, IAPage } from './ia-generation-prompt'

export interface SiteContext {
  websiteName: string
  targetAudience: string
  pages: IAPage[]
}

export interface PageContentPromptParams {
  pageSlug: string
  pageTitle: string
  iaMetadata: IAMetadata
  siteContext: SiteContext
  componentSchemas: string
  /** Original user prompt/PRD - used as source content for verbatim copy extraction */
  originalPrompt?: string
}

/**
 * Builds a focused prompt for generating content for ONE specific page.
 * Receives IA metadata from Phase 1 and component schemas.
 */
export function buildPageContentPrompt(params: PageContentPromptParams): string {
  const { pageSlug, pageTitle, iaMetadata, siteContext, componentSchemas, originalPrompt } = params
  const segments: string[] = []

  // Page identity
  segments.push(`# Content Generation: ${pageTitle} Page`)
  segments.push('')
  segments.push(`You are generating content for the "${pageSlug}" page.`)
  segments.push('')

  // CRITICAL: Action priority - populatePageContent is the PRIMARY required action
  segments.push('## ⚠️ REQUIRED ACTION (MUST DO)')
  segments.push('')
  segments.push('**You MUST call the `populatePageContent` tool to create this page.**')
  segments.push('')
  segments.push('Your job is simple:')
  segments.push('1. Design the page components based on the guidelines below')
  segments.push('2. Call `populatePageContent` with the `pageSlug` and `components` array')
  segments.push('')
  segments.push('**The `searchImages` tool is OPTIONAL** - only use it if you want to add background images.')
  segments.push('You can call `populatePageContent` immediately with placeholder image URLs like "pexels:search:query".')
  segments.push('')
  segments.push('**DO NOT** get stuck searching for images. Call `populatePageContent` to complete the task.')
  segments.push('')

  // Page purpose from IA
  segments.push('## Page Purpose (from Information Architecture)')
  segments.push('')
  segments.push(`**Purpose**: ${iaMetadata.purpose}`)
  segments.push(`**Target Audience**: ${iaMetadata.targetAudience}`)
  segments.push(`**Primary Question to Answer**: ${iaMetadata.primaryQuestion}`)
  segments.push(`**Journey Stage**: ${iaMetadata.journeyStage}`)
  segments.push('')

  // Section intents from Phase 1
  segments.push('## Section Intents (from Information Architecture)')
  segments.push('')
  segments.push('These are the high-level descriptions of what this page needs:')
  const intents = iaMetadata.sectionIntents
  intents.forEach((intent, i) => {
    segments.push(`${i + 1}. ${intent}`)
  })
  segments.push('')

  // Component selection guidance - actual components and their usage rules come from componentSchemas
  segments.push('## Component Selection')
  segments.push('')
  segments.push('For each section intent, pick the BEST component from the Component Catalog below.')
  segments.push('Each component in the catalog includes usage directives - follow them carefully.')
  segments.push('')
  segments.push('**RULES:**')
  segments.push('1. Read each section intent and pick the component that BEST matches the purpose')
  segments.push('2. Every page MUST start with `navbar` and end with `footer`')
  segments.push('3. ONLY use component types from the Component Catalog - never invent new ones')
  segments.push('4. Follow the component directives (usage instructions) from the catalog')
  segments.push('')

  // Site context for narrative consistency
  segments.push('## Site Context')
  segments.push('')
  segments.push(`Website: ${siteContext.websiteName}`)
  segments.push(`Overall Target Audience: ${siteContext.targetAudience}`)
  segments.push('')
  segments.push('Other pages in this site:')
  siteContext.pages
    .filter(p => p.slug !== pageSlug)
    .forEach(p => {
      segments.push(`  - ${p.title} (/${p.slug}): ${p.iaMetadata.purpose}`)
    })
  segments.push('')
  segments.push('Use this context to:')
  segments.push('- Maintain consistent tone and messaging')
  segments.push('- Create relevant internal links (e.g., CTA to Contact page)')
  segments.push('- Avoid duplicating content that belongs on other pages')
  segments.push('')

  // Page layout structure (mandatory)
  segments.push('## Page Layout Structure (MANDATORY)')
  segments.push('')
  segments.push('Every page MUST follow this structure:')
  segments.push('')
  segments.push('1. **navbar** (FIRST) - Global navigation bar, same on all pages')
  segments.push('2. **[Page-specific content components]** - The main content that varies by page')
  segments.push('3. **footer** (LAST) - Global footer, same on all pages')
  segments.push('')
  segments.push('IMPORTANT:')
  segments.push('- navbar and footer are GLOBAL elements - they appear on every page with consistent content')
  segments.push('- Do NOT skip navbar or footer - they are required structural elements')
  segments.push('- The page-specific content goes BETWEEN navbar and footer')
  segments.push('')

  // Navigation constraint - menu items must link to existing pages only
  segments.push('**CRITICAL Navigation Constraint:**')
  segments.push('navbar.menuItems MUST ONLY contain links to pages that exist in this site.')
  segments.push('Available pages for navigation links:')
  siteContext.pages.forEach(p => {
    segments.push(`  - label: "${p.title}", href: "/${p.slug}"`)
  })
  segments.push('Do NOT create menu items linking to pages not listed above (e.g., do not link to /features, /pricing, /blog unless they exist above).')
  segments.push('')

  // Source content (PRD/original prompt) - CRITICAL for verbatim copy
  if (originalPrompt) {
    segments.push('## SOURCE CONTENT (CRITICAL - USE VERBATIM)')
    segments.push('')
    segments.push('The following is the original PRD/specification from the user.')
    segments.push('**YOU MUST use copy from this source EXACTLY as written when it applies to this page.**')
    segments.push('')
    segments.push('<source-content>')
    segments.push(originalPrompt)
    segments.push('</source-content>')
    segments.push('')
    segments.push('### CRITICAL RULES for Source Content:')
    segments.push('1. If the source content provides exact copy for this page\'s sections, use that copy VERBATIM')
    segments.push('2. Do NOT paraphrase, rephrase, or "improve" the source copy')
    segments.push('3. If the source specifies exact stats (e.g., "8,247 pages", "$2M revenue"), use those EXACT numbers')
    segments.push('4. If the source provides headlines, taglines, or CTAs, use them EXACTLY')
    segments.push('5. Only generate original content for sections NOT covered in the source')
    segments.push('6. Do NOT add testimonials, case studies, or founder credentials unless the source provides them')
    segments.push('7. Do NOT invent company history, team details, or specific claims not in the source')
    segments.push('')
  }

  // Component schemas
  segments.push('## Available Components')
  segments.push('')
  segments.push('Use these components to build the page content:')
  segments.push('')
  segments.push(componentSchemas)
  segments.push('')

  // Content guidelines
  segments.push('## Content Guidelines')
  segments.push('')
  segments.push('1. **Match the journey stage**:')
  switch (iaMetadata.journeyStage) {
    case 'awareness':
      segments.push('   - Focus on problem/solution introduction')
      segments.push('   - Use attention-grabbing headlines')
      segments.push('   - Keep messaging broad and accessible')
      break
    case 'interest':
      segments.push('   - Build curiosity and show value')
      segments.push('   - Share story and differentiators')
      segments.push('   - Create emotional connection')
      break
    case 'consideration':
      segments.push('   - Provide proof and specifics')
      segments.push('   - Show portfolio, case studies, testimonials')
      segments.push('   - Address objections')
      break
    case 'decision':
      segments.push('   - Make next steps crystal clear')
      segments.push('   - Reduce friction to conversion')
      segments.push('   - Include strong call-to-action')
      break
  }
  segments.push('')
  segments.push('2. **Answer the primary question**: Every component should help answer:')
  segments.push(`   "${iaMetadata.primaryQuestion}"`)
  segments.push('')
  segments.push('3. **Link to other pages**: Include relevant CTAs and links to other site pages.')
  segments.push('')

  // Hero background image instructions (MANDATORY for visual impact)
  segments.push('## Hero Visual Impact (MANDATORY)')
  segments.push('')
  segments.push('### Hero Height (Creates Immersive First Impression)')
  segments.push('')
  segments.push('Hero components support a `height` property in the content object:')
  segments.push('- `"small"`: 50-60vh (compact hero)')
  segments.push('- `"medium"`: 60-80vh (balanced)')
  segments.push('- `"large"`: 75-90vh (spacious, impactful)')
  segments.push('- `"full"`: 100vh (full viewport, maximum impact)')
  segments.push('')
  segments.push('**CRITICAL HEIGHT RULES:**')
  segments.push('- **Homepage heroes MUST use `"height": "full"`** for immersive first impression')
  segments.push('- Interior page heroes should use `"height": "medium"` or `"height": "large"`')
  segments.push('- NEVER leave height unset on homepage heroes - this creates weak, wimpy layouts!')
  segments.push('')
  segments.push('### Hero Background Images (OPTIONAL)')
  segments.push('')
  segments.push('If you want to add background images to heroes, you have TWO options:')
  segments.push('')
  segments.push('**Option A**: Use placeholder URLs in the format `pexels:search:your query here`')
  segments.push('  - These will be resolved to real images automatically after page creation')
  segments.push('  - Example: `"src": "pexels:search:modern dental clinic interior"`')
  segments.push('')
  segments.push('**Option B**: Call `searchImages` tool first, then use the returned URLs')
  segments.push('')
  segments.push('If using searchImages, follow this pattern:')
  segments.push('')
  segments.push('1. **Query Construction**: Base query on the business type and page purpose')
  segments.push('   - Home page: "[business type] interior professional atmosphere" (e.g., "coffee shop interior warm cozy")')
  segments.push('   - About page: "[business type] team professional"')
  segments.push('   - Contact page: "[business type] storefront exterior"')
  segments.push('')
  segments.push('2. **searchImages Parameters**:')
  segments.push('   - query: Industry-relevant query')
  segments.push('   - count: 1')
  segments.push('   - orientation: "landscape"')
  segments.push('   - size: "large"')
  segments.push('')
  segments.push('3. **Map Result to Hero** (ALWAYS include overlay AND height):')
  segments.push('Example content object:')
  segments.push('"content": {')
  segments.push('  "heading": "...",')
  segments.push('  "subheading": "...",')
  segments.push('  "height": "full",')
  segments.push('  "background": {')
  segments.push('    "image": {')
  segments.push('      "src": "[first image src from searchImages]",')
  segments.push('      "alt": "[first image alt from searchImages]"')
  segments.push('    },')
  segments.push('    "overlayColor": "rgba(0, 0, 0, 0.5)",')
  segments.push('    "overlayOpacity": 0.5')
  segments.push('  }')
  segments.push('}')
  segments.push('')
  segments.push('**CRITICAL: ALWAYS add overlayColor and overlayOpacity when using background images!**')
  segments.push('Without an overlay, text will be unreadable against busy background images.')
  segments.push('')
  segments.push('**Example**: For a coffee shop home page hero:')
  segments.push('- Call: searchImages("coffee shop interior warm lighting cozy atmosphere", 1, "landscape", "large")')
  segments.push('- Result: { images: [{ src: "https://...", alt: "Cozy coffee shop" }] }')
  segments.push('- Hero with full height and background overlay:')
  segments.push('Example hero component:')
  segments.push('{')
  segments.push('  "type": "hero-simple",')
  segments.push('  "content": {')
  segments.push('    "heading": "Your Perfect Cup Awaits",')
  segments.push('    "subheading": "Artisan coffee in a cozy atmosphere",')
  segments.push('    "height": "full",')
  segments.push('    "ctaButtons": [{ "label": "View Menu", "href": "#menu" }],')
  segments.push('    "background": {')
  segments.push('      "image": { "src": "https://...", "alt": "Cozy coffee shop" },')
  segments.push('      "overlayColor": "rgba(0, 0, 0, 0.5)",')
  segments.push('      "overlayOpacity": 0.5')
  segments.push('    }')
  segments.push('  }')
  segments.push('}')
  segments.push('')
  // Visual rhythm and background layers (CRITICAL for v0.dev quality)
  segments.push('## Visual Rhythm & Background Layers (CRITICAL for Professional Look)')
  segments.push('')
  segments.push('**Modern websites need VISUAL VARIETY - not all-white backgrounds!**')
  segments.push('')
  segments.push('Use the `background` property on sections to create visual rhythm:')
  segments.push('')
  segments.push('Example section background:')
  segments.push('{')
  segments.push('  "type": "feature-grid",')
  segments.push('  "content": {')
  segments.push('    "heading": "...",')
  segments.push('    "background": { "color": "muted" },')
  segments.push('    "items": [...]')
  segments.push('  }')
  segments.push('}')
  segments.push('')
  segments.push('**Available background colors:**')
  segments.push('- Omit `background.color`: White/light background')
  segments.push('- `"muted"`: Subtle gray (bg-muted/50)')
  segments.push('- `"primary"`: Brand color background (bg-primary)')
  segments.push('- `"accent"`: Accent color (bg-accent)')
  segments.push('')
  segments.push('**PATTERN FOR VISUAL RHYTHM (Follow this!):**')
  segments.push('1. Hero: Full-height with image background')
  segments.push('2. First content section: White')
  segments.push('3. Second content section: Muted (light gray)')
  segments.push('4. Third content section: White')
  segments.push('5. Fourth content section: Muted or Primary')
  segments.push('6. CTA section: Primary (brand color) for emphasis')
  segments.push('7. Footer: White or Muted')
  segments.push('')
  segments.push('**Example full page flow:**')
  segments.push('- Hero: Image background + overlay ✓')
  segments.push('- Services (feature-grid): omit `background.color`')
  segments.push('- Why Choose Us (feature-grid): `"background": { "color": "muted" }`')
  segments.push('- Testimonials: omit `background.color`')
  segments.push('- CTA: `"background": { "color": "primary" }`')
  segments.push('- Footer: standard')
  segments.push('')
  segments.push('**⚠️ AVOID: All sections with no background (creates flat, boring pages)**')
  segments.push('')

  // Icons for visual polish (CRITICAL for v0.dev quality)
  segments.push('## Icons for Visual Polish (CRITICAL)')
  segments.push('')
  segments.push('**Professional websites use icons to enhance content - not just text!**')
  segments.push('')
  segments.push('Every `feature-grid` and `feature-list` item SHOULD have an icon. Use Lucide icon names:')
  segments.push('')
  segments.push('**Common icon mappings by content type:**')
  segments.push('| Content Type | Icon Name |')
  segments.push('|--------------|-----------|')
  segments.push('| Location/Address | `MapPin` |')
  segments.push('| Phone/Call | `Phone` |')
  segments.push('| Hours/Time | `Clock` |')
  segments.push('| Email | `Mail` |')
  segments.push('| WiFi | `Wifi` |')
  segments.push('| Coffee/Drink | `Coffee` |')
  segments.push('| Food/Menu | `UtensilsCrossed` |')
  segments.push('| Home/House | `Home` |')
  segments.push('| Settings/Gear | `Settings` |')
  segments.push('| User/Profile | `User` |')
  segments.push('| Team/People | `Users` |')
  segments.push('| Star/Rating | `Star` |')
  segments.push('| Heart/Love | `Heart` |')
  segments.push('| Check/Complete | `CheckCircle` |')
  segments.push('| Shield/Security | `Shield` |')
  segments.push('| Wrench/Service | `Wrench` |')
  segments.push('| Droplet/Water | `Droplets` |')
  segments.push('| Flame/Fire | `Flame` |')
  segments.push('| Zap/Fast | `Zap` |')
  segments.push('| Award/Quality | `Award` |')
  segments.push('| Briefcase/Work | `Briefcase` |')
  segments.push('| Calendar/Schedule | `Calendar` |')
  segments.push('| Dollar/Price | `DollarSign` |')
  segments.push('| Globe/World | `Globe` |')
  segments.push('| Building/Office | `Building2` |')
  segments.push('| Scale/Legal | `Scale` |')
  segments.push('| Gavel/Law | `Gavel` |')
  segments.push('| Target/Goal | `Target` |')
  segments.push('| Rocket/Launch | `Rocket` |')
  segments.push('| Code/Dev | `Code` |')
  segments.push('| Palette/Design | `Palette` |')
  segments.push('| Camera/Photo | `Camera` |')
  segments.push('| Video | `Video` |')
  segments.push('| Headphones/Audio | `Headphones` |')
  segments.push('| MessageCircle/Chat | `MessageCircle` |')
  segments.push('| Send/Submit | `Send` |')
  segments.push('| Download | `Download` |')
  segments.push('| Upload | `Upload` |')
  segments.push('| Lock/Secure | `Lock` |')
  segments.push('| Key/Access | `Key` |')
  segments.push('| Leaf/Eco | `Leaf` |')
  segments.push('| Sparkles/Studio | `Sparkles` |')
  segments.push('| Gift/Offer | `Gift` |')
  segments.push('| Package/Product | `Package` |')
  segments.push('| Truck/Delivery | `Truck` |')
  segments.push('| CreditCard/Payment | `CreditCard` |')
  segments.push('| BarChart/Analytics | `BarChart3` |')
  segments.push('| PieChart/Stats | `PieChart` |')
  segments.push('| TrendingUp/Growth | `TrendingUp` |')
  segments.push('| Lightbulb/Idea | `Lightbulb` |')
  segments.push('| Puzzle/Solution | `Puzzle` |')
  segments.push('')
  segments.push('**Example with icons:**')
  segments.push('{')
  segments.push('  "type": "feature-grid",')
  segments.push('  "content": {')
  segments.push('    "heading": "Visit Us",')
  segments.push('    "items": [')
  segments.push('      { "icon": "MapPin", "title": "Location", "description": "42 Main Street, Brunswick" },')
  segments.push('      { "icon": "Clock", "title": "Hours", "description": "Mon-Fri 6am-4pm" },')
  segments.push('      { "icon": "Phone", "title": "Phone", "description": "(03) 9123 4567" },')
  segments.push('      { "icon": "Wifi", "title": "Amenities", "description": "Free WiFi Available" }')
  segments.push('    ]')
  segments.push('  }')
  segments.push('}')
  segments.push('')
  segments.push('**⚠️ ALWAYS include icons on feature-grid items. Icon-less grids look unpolished!**')
  segments.push('')

  // Copywriting rules (CRITICAL for professional quality)
  segments.push('## Copywriting Rules (CRITICAL for Professional Quality)')
  segments.push('')
  segments.push('### Active Voice (MANDATORY)')
  segments.push('')
  segments.push('**ALL copy MUST use active voice. Passive voice sounds weak and corporate.**')
  segments.push('')
  segments.push('| ❌ PASSIVE (WRONG) | ✅ ACTIVE (CORRECT) |')
  segments.push('|-------------------|---------------------|')
  segments.push('| "The app will be installed" | "Install the app" |')
  segments.push('| "Your order has been placed" | "We received your order" |')
  segments.push('| "The project was completed by our team" | "Our team completed the project" |')
  segments.push('| "Results can be seen within days" | "See results within days" |')
  segments.push('| "Services are provided by experts" | "Experts provide services" |')
  segments.push('| "Your data is protected by encryption" | "Encryption protects your data" |')
  segments.push('| "Issues will be resolved quickly" | "We resolve issues quickly" |')
  segments.push('| "A consultation can be scheduled" | "Schedule a consultation" |')
  segments.push('')
  segments.push('**Active voice pattern**: Subject + Verb + Object')
  segments.push('**Passive voice pattern**: Object + "is/was/will be" + Past Participle + "by" Subject')
  segments.push('')
  segments.push('**Check your copy**: If you can add "by zombies" after the verb and it makes grammatical sense, it\'s passive voice!')
  segments.push('- "The app will be installed [by zombies]" ← Passive, rewrite it')
  segments.push('- "Install the app" ← Cannot add "by zombies", this is active voice ✓')
  segments.push('')
  segments.push('### Title Case (MANDATORY for Headings and Buttons)')
  segments.push('')
  segments.push('**Headlines, subheadlines, and button labels MUST use Title Case (Chicago style).**')
  segments.push('')
  segments.push('| ❌ WRONG | ✅ CORRECT |')
  segments.push('|----------|-----------|')
  segments.push('| "Welcome to our website" | "Welcome to Our Website" |')
  segments.push('| "Get started today" | "Get Started Today" |')
  segments.push('| "Schedule a free consultation" | "Schedule a Free Consultation" |')
  segments.push('| "Learn more about our services" | "Learn More About Our Services" |')
  segments.push('')
  segments.push('**Title Case Rules:**')
  segments.push('- Capitalize first and last words')
  segments.push('- Capitalize nouns, verbs, adjectives, adverbs')
  segments.push('- Lowercase articles (a, an, the), prepositions (to, for, with), conjunctions (and, or, but)')
  segments.push('- Exception: Capitalize prepositions 4+ letters (About, After, Between)')
  segments.push('')
  segments.push('### Numerals (MANDATORY for Counts)')
  segments.push('')
  segments.push('**Use digits for ALL numbers in marketing copy, especially counts and stats.**')
  segments.push('')
  segments.push('| ❌ WRONG | ✅ CORRECT |')
  segments.push('|----------|-----------|')
  segments.push('| "Eight projects completed" | "8 Projects Completed" |')
  segments.push('| "Over three hundred customers" | "Over 300 Customers" |')
  segments.push('| "Twenty years experience" | "20 Years Experience" |')
  segments.push('| "Trusted by thousands" | "Trusted by 10,000+ Clients" |')
  segments.push('')
  segments.push('**Why digits?**')
  segments.push('- Faster to scan and comprehend')
  segments.push('- More impactful and credible')
  segments.push('- Better for statistics sections')
  segments.push('')

  // Content formatting rules (CRITICAL for quality)
  segments.push('## Content Formatting Rules (CRITICAL)')
  segments.push('')
  segments.push('**DO NOT use raw HTML in content strings:**')
  segments.push('- ❌ WRONG: "Hours: 6am-4pm<br>Phone: 123-456"')
  segments.push('- ✅ RIGHT: Put each piece of information in a separate field or array item')
  segments.push('')
  segments.push('**CTA Buttons MUST have visible, specific text labels:**')
  segments.push('- ❌ WRONG: ctaButtons: [{ href: "#menu" }] // No label!')
  segments.push('- ❌ WRONG: ctaButtons: [{ label: "Submit", href: "/contact" }] // Too generic!')
  segments.push('- ❌ WRONG: ctaButtons: [{ label: "Click Here", href: "/about" }] // Meaningless!')
  segments.push('- ✅ RIGHT: ctaButtons: [{ label: "View Our Menu", href: "#menu" }]')
  segments.push('- ✅ RIGHT: ctaButtons: [{ label: "Send Message", href: "/contact" }] // Specific action')
  segments.push('- ✅ RIGHT: ctaButtons: [{ label: "Start Free Trial", href: "/signup" }] // Clear outcome')
  segments.push('')
  segments.push('**Avoid generic button labels - use specific action words:**')
  segments.push('- ❌ BAD: "Submit", "Send", "Click", "Go", "OK", "Yes", "No", "Cancel"')
  segments.push('- ✅ GOOD: "Send Message", "Request Demo", "Start Free Trial", "Get Started"')
  segments.push('- ✅ GOOD: "Subscribe to Newsletter", "Download Brochure", "Schedule Call"')
  segments.push('')
  segments.push('**feature-grid items should each be separate objects:**')
  segments.push('- For location/contact info, create SEPARATE items for address, hours, phone, etc.')
  segments.push('- For menu items, create SEPARATE items for each product with title, price, description')
  segments.push('')
  segments.push('**Example - Visit Us section with feature-grid:**')
  segments.push('{')
  segments.push('  "type": "feature-grid",')
  segments.push('  "content": {')
  segments.push('    "heading": "Visit Us",')
  segments.push('    "subheading": "We can\'t wait to serve you",')
  segments.push('    "items": [')
  segments.push('      { "title": "Location", "description": "42 Main Street, Brunswick" },')
  segments.push('      { "title": "Hours", "description": "Mon-Fri 6am-4pm, Sat-Sun 7am-3pm" },')
  segments.push('      { "title": "Phone", "description": "(03) 9123 4567" },')
  segments.push('      { "title": "Amenities", "description": "Free WiFi Available" }')
  segments.push('    ]')
  segments.push('  }')
  segments.push('}')
  segments.push('')

  // CRITICAL VALIDATION
  segments.push('## CRITICAL VALIDATION BEFORE OUTPUT')
  segments.push('')
  segments.push('⚠️ BEFORE generating your output, CHECK EACH COMPONENT:')
  segments.push('')
  segments.push('1. **Type validation**: Every component `type` MUST be from the Component Catalog above')
  segments.push('2. **No invented types**: Do NOT create types like "services-overview" or "process-steps"')
  segments.push('3. **Use generic components**: For custom section concepts, use `feature-grid`, `text-block`, or `card-grid`')
  segments.push('')

  // Component region assignment (CRITICAL for layout)
  segments.push('## Component Region Assignment (CRITICAL for Layout)')
  segments.push('')
  segments.push('The `region` property controls WHERE a component renders on the page:')
  segments.push('')
  segments.push('| Component Type | Region Property | Result |')
  segments.push('|---------------|-----------------|--------|')
  segments.push('| navbar | `"region": "header"` | Renders at absolute top, overlays hero |')
  segments.push('| footer | `"region": "footer"` | Renders at page bottom |')
  segments.push('| All others | (omit region) | Renders in main content area |')
  segments.push('')
  segments.push('**⚠️ CRITICAL**: If you omit `region: "header"` from navbar, it will render IN THE MIDDLE of the page!')
  segments.push('')

  // Output format
  segments.push('## Output')
  segments.push('')
  segments.push('Call populatePageContent with:')
  segments.push('Tool argument shape:')
  segments.push('{')
  segments.push(`  "pageSlug": "${pageSlug}",`)
  segments.push('  "components": [')
  segments.push('    { "type": "navbar", "region": "header", "content": { "logo": { "text": "Brand" }, "menuItems": [...] } },')
  segments.push('    { "type": "hero-simple", "content": { "heading": "...", "subheading": "...", "ctaButtons": [{ "label": "CTA Text", "href": "#section" }] } },')
  segments.push('    { "type": "feature-grid", "content": { "heading": "...", "items": [{ "title": "...", "description": "..." }] } },')
  segments.push('    { "type": "cta-simple", "content": { "heading": "...", "ctaButtons": [{ "label": "Contact Us", "href": "/contact" }] } },')
  segments.push('    { "type": "footer", "region": "footer", "content": { "copyright": "...", "columns": [...] } }')
  segments.push('  ]')
  segments.push('}')
  segments.push('')
  segments.push('**REMINDER**: Every ctaButton MUST have a "label" field with visible text. Do NOT omit labels.')
  segments.push('')
  segments.push('**REMINDER**: navbar MUST have `"region": "header"` and footer MUST have `"region": "footer"`.')

  return segments.join('\n')
}
