#!/usr/bin/env tsx
/**
 * Test Sandbox with Tarball
 *
 * Tests the new tarball-based sandbox creation approach.
 * This script creates a sandbox using the SDK's tarball source parameter.
 *
 * Usage:
 *   pnpm tsx scripts/test-sandbox-tarball.ts
 */

import { Sandbox } from '@vercel/sandbox'
import * as fs from 'fs'
import * as path from 'path'
import { config } from 'dotenv'

// Load environment variables from .env.local
config({ path: '.env.local' })

const TARBALL_PATH = path.join(process.cwd(), 'tmp', 'sandbox-template.tar.gz')
const S3_PUBLIC_BASE_URL = process.env.STUDIO_MEDIA_STORAGE_S3_PUBLIC_BASE_URL?.replace(/ /g, '%20')
const TARBALL_URL = process.env.TARBALL_URL || (S3_PUBLIC_BASE_URL ? `${S3_PUBLIC_BASE_URL}/sandbox-templates/sandbox-template.tar.gz` : '')
const TEST_WEBSITE_ID = 'cmk0ywhtq003dkbnyvkudd8d9' // Test website

function log(message: string): void {
  console.log(`[test-sandbox] ${message}`)
}

async function main(): Promise<void> {
  log('Starting sandbox test...')

  if (!TARBALL_URL) {
    throw new Error('Set TARBALL_URL or STUDIO_MEDIA_STORAGE_S3_PUBLIC_BASE_URL before testing tarball sandboxes')
  }

  // Check credentials
  const teamId = process.env.VERCEL_TEAM_ID
  const projectId = process.env.VERCEL_PROJECT_ID
  const token = process.env.VERCEL_TOKEN

  if (!teamId || !projectId || !token) {
    throw new Error('Missing Vercel credentials: VERCEL_TEAM_ID, VERCEL_PROJECT_ID, VERCEL_TOKEN')
  }
  log(`Using team: ${teamId}, project: ${projectId}`)

  // Check tarball exists locally (for size reporting)
  if (fs.existsSync(TARBALL_PATH)) {
    const tarballStats = fs.statSync(TARBALL_PATH)
    log(`Local tarball size: ${(tarballStats.size / (1024 * 1024)).toFixed(2)} MB`)
  }
  log(`Tarball URL: ${TARBALL_URL}`)

  // Create sandbox using SDK's tarball source parameter
  // This is cleaner than manually uploading + extracting
  log('Creating sandbox with tarball source (this may take a minute)...')
  const startTime = Date.now()

  const sandbox = await Sandbox.create({
    teamId,
    projectId,
    token,
    source: {
      type: 'tarball',
      url: TARBALL_URL,
    },
    resources: { vcpus: 2 },
    timeout: 30 * 60 * 1000, // 30 minutes
    ports: [3000], // CRITICAL: Exposes port to public URL
    runtime: 'node24',
  })

  const createTime = Date.now() - startTime
  log(`Sandbox created in ${(createTime / 1000).toFixed(1)}s`)
  log(`Sandbox ID: ${sandbox.id}`)

  // Write website-specific .env.local
  log('Writing .env.local...')
  const databaseUrl = process.env.DATABASE_URL || ''
  const directUrl = process.env.DIRECT_URL || ''

  await sandbox.writeFiles([
    {
      path: '.env.local',
      content: Buffer.from(`# Generated by Catalyst Studio sandbox test
# Website-specific configuration
HEAD_RUNTIME_WEBSITE_ID=${TEST_WEBSITE_ID}
HEAD_RUNTIME_PROVIDER=ucs

# Database connection (required for UCS provider)
DATABASE_URL="${databaseUrl}"
DIRECT_URL="${directUrl}"

# Cache configuration
HEAD_RUNTIME_CACHE_TTL_SECONDS=30
`),
    },
  ])

  // Fix execute permissions on bin scripts (tarball from Windows loses permissions)
  log('Fixing execute permissions on bin scripts...')
  const chmodResult = await sandbox.runCommand({
    cmd: 'chmod',
    args: ['-R', '+x', 'node_modules/.bin'],
  })
  log(`chmod result: exitCode=${chmodResult.exitCode}`)
  if (chmodResult.exitCode !== 0) {
    log(`chmod stderr: ${await chmodResult.stderr()}`)
  }

  // NOTE: Prisma generate is NO LONGER needed!
  // The tarball now includes pre-generated Linux Prisma binaries (rhel-openssl-3.0.x)
  // and pre-compiled Next.js build (.next directory)
  log('Skipping prisma generate (pre-included in tarball)')

  // Check what's in the sandbox
  log('Checking sandbox contents...')
  const lsResult = await sandbox.runCommand({
    cmd: 'ls',
    args: ['-la'],
  })
  log(`ls -la:\n${await lsResult.stdout()}`)

  // Check if package.json exists
  const catResult = await sandbox.runCommand({
    cmd: 'cat',
    args: ['package.json'],
  })
  log(`package.json exists: ${catResult.exitCode === 0}`)

  // Start production server detached (pre-compiled in tarball)
  log('Starting production server (detached)...')
  const devResult = await sandbox.runCommand({
    cmd: 'npm',
    args: ['start'],
    detached: true,
  })
  log(`npm start launched (detached), exitCode=${devResult.exitCode}`)

  // Wait for production server to initialize (much faster than dev)
  log('Waiting 5s for production server to initialize...')
  await new Promise(resolve => setTimeout(resolve, 5000))

  // Poll for server readiness instead of fixed wait
  const previewUrl = sandbox.domain(3000)
  log(`Preview URL: ${previewUrl}`)
  log('Polling for server readiness...')

  const maxAttempts = 30
  const pollInterval = 2000 // 2 seconds

  for (let i = 1; i <= maxAttempts; i++) {
    try {
      const response = await fetch(previewUrl, { method: 'HEAD' })
      const contentLength = response.headers.get('content-length')
      log(`Poll ${i}/${maxAttempts}: status=${response.status}, content-length=${contentLength}`)

      // Check if we're getting actual content (not empty response)
      if (response.ok && contentLength && parseInt(contentLength) > 0) {
        log('Server is ready!')
        break
      }
    } catch (err) {
      log(`Poll ${i}/${maxAttempts}: ${err instanceof Error ? err.message : 'error'}`)
    }

    if (i === maxAttempts) {
      log('Warning: Max poll attempts reached, server may not be ready')
    } else {
      await new Promise(resolve => setTimeout(resolve, pollInterval))
    }
  }

  log('='.repeat(60))
  log(`✅ SUCCESS! Sandbox is ready.`)
  log(`Preview URL: ${previewUrl}`)
  log(`Website ID: ${TEST_WEBSITE_ID}`)
  log('='.repeat(60))
  log('')
  log('The sandbox will remain active for 30 minutes.')
  log('Press Ctrl+C to exit (sandbox will continue running).')
  log('')

  // Keep the script running so we can test
  await new Promise(() => {})
}

main().catch(err => {
  console.error('[test-sandbox] Error:', err)
  process.exit(1)
})
