/**
 * Value Objects - Centralized schema registry and utilities
 *
 * This module provides utilities for working with Zod schemas as value objects,
 * converting them to type strings for LLMs and FieldSchema for property editors.
 */

// Re-export utilities
export { zodToTypeString } from './utils/zod-to-type-string'
export { zodToFieldSchema } from './utils/zod-to-field-schema'
export { getAllValueObjectNames } from './registry-lookup'

// Re-export registry, lookup functions, and types
export {
  // Lookup functions
  getSchema,
  getTypeString,
  getFieldSchema,
  // ValueObjectName type
  type ValueObjectName,
  // All schemas (alphabetically)
  AddressSchema,
  AnchorLinkSchema,
  AuthorSchema,
  AutoFillSchema,
  BadgeSchema,
  BlogPostItemSchema,
  BlogPostMetadataSchema,
  CardItemSchema,
  CategorySchema,
  ComparisonFeatureSchema,
  ComparisonProductSchema,
  ComponentListSchema,
  ConsentSchema,
  ContactInfoSchema,
  ContentAreaSchema,
  CTAButtonSchema,
  EducationEntrySchema,
  EmailLinkSchema,
  ExperienceEntrySchema,
  ExternalLinkSchema,
  FAQSchema,
  FeatureItemSchema,
  FilterSchema,
  FooterColumnSchema,
  FooterNewsletterSchema,
  FormFieldSchema,
  HeroSlideSchema,
  ImageSchema,
  LinkSchema,
  LogoSchema,
  MediaReferenceSchema,
  MenuItemSchema,
  NavBarSearchSchema,
  PageReferenceSchema,
  PhoneLinkSchema,
  PhoneNumberSchema,
  PricingFeatureSchema,
  PricingTierSchema,
  RatingSchema,
  ShowcaseSectionSchema,
  SideMenuSectionSchema,
  SmartLinkSchema,
  SocialLinkSchema,
  StatItemSchema,
  SubmitButtonSchema,
  TabItemSchema,
  TagSchema,
  TeamMemberSchema,
  TestimonialSchema,
  TimelineActionSchema,
  TimelineEventSchema,
  VideoSourceSchema,
  // All types (alphabetically)
  type Address,
  type AnchorLink,
  type Author,
  type AutoFill,
  type Badge,
  type BlogPostItem,
  type BlogPostMetadata,
  type CardItem,
  type Category,
  type ComparisonFeature,
  type ComparisonProduct,
  type ComponentList,
  type Consent,
  type ContactInfo,
  type ContentArea,
  type CTAButton,
  type EducationEntry,
  type EmailLink,
  type ExperienceEntry,
  type ExternalLink,
  type FAQ,
  type FeatureItem,
  type Filter,
  type FooterColumn,
  type FooterNewsletter,
  type FormField,
  type HeroSlide,
  type Image,
  type Link,
  type Logo,
  type MediaReference,
  type MenuItem,
  type NavBarSearch,
  type PageReference,
  type PhoneLink,
  type PhoneNumber,
  type PricingFeature,
  type PricingTier,
  type Rating,
  type ShowcaseSection,
  type SideMenuSection,
  type SmartLink,
  type SocialLink,
  type StatDelta,
  type StatItem,
  type SubmitButton,
  type TabItem,
  type Tag,
  type TeamMember,
  type Testimonial,
  type TimelineAction,
  type TimelineEvent,
  type VideoSource,
} from './registry'
