import { ComponentType as CmsComponentType } from '@/lib/studio/components/cms/_core/types'

/**
 * Component Instance Interface
 * 
 * Defines the data structure for individual components in the Site Builder.
 * This interface replaces the previous string-based component representation
 * with a rich object structure that can store properties, content, and styles.
 */

/**
 * Content structure for component instances
 */
export interface ComponentContent {
  /** Text content for components that display text */
  text?: string
  /** Array of image URLs or paths */
  images?: string[]
  /** Array of links with URL and label */
  links?: Array<{
    url: string
    label: string
  }>
}

/**
 * Responsive styles structure for component instances
 */
export interface ComponentStyles {
  /** Styles for desktop viewport */
  desktop?: Record<string, any>
  /** Styles for tablet viewport */
  tablet?: Record<string, any>
  /** Styles for mobile viewport */
  mobile?: Record<string, any>
}

/**
 * Metadata for component instances
 */
export interface ComponentMetadata {
  /** Whether the component is locked from editing */
  locked?: boolean
  /** Whether the component is visible in the UI */
  visible?: boolean
  /** Whether the component was generated by AI */
  aiGenerated?: boolean
  /** Whether this component is global */
  isGlobal?: boolean
}

/**
 * Main ComponentInstance interface
 * 
 * Represents a single component instance within a page's component tree.
 * Each instance has a unique ID and can have parent-child relationships
 * for building hierarchical layouts.
 */
export interface ComponentInstance {
  /** Unique component identifier (cuid) */
  id: string
  
  /** Component type identifier (e.g., "hero-banner", "navigation") */
  type: string

  /** Canonical CMS component type enum value */
  componentType?: CmsComponentType

  /** Canonical WebsiteComponentType ID (persisted from importer) */
  componentTypeId?: string

  /** WebsiteComponentType identifier stored by older import services */
  typeId?: string
  
  /** Parent component ID for hierarchy, null for root components */
  parentId: string | null
  
  /** Order within parent container, 0-based */
  position: number
  
  /** Component-specific properties and configuration */
  props: Record<string, any>
  
  /** Content data for the component */
  content: ComponentContent
  
  /** Responsive styles for the component */
  styles: ComponentStyles
  
  /** Component metadata and flags */
  metadata: ComponentMetadata

}

/**
 * Array type for collections of component instances
 */
export type ComponentInstanceArray = ComponentInstance[]

/**
 * Type guard to check if a value is a ComponentInstance
 */
export function isComponentInstance(value: any): value is ComponentInstance {
  return (
    typeof value === 'object' &&
    value !== null &&
    typeof value.id === 'string' &&
    typeof value.type === 'string' &&
    (value.componentType === undefined || typeof value.componentType === 'string') &&
    (value.componentTypeId === undefined || typeof value.componentTypeId === 'string') &&
    (value.typeId === undefined || typeof value.typeId === 'string') &&
    (value.parentId === null || typeof value.parentId === 'string') &&
    typeof value.position === 'number' &&
    typeof value.props === 'object' &&
    typeof value.content === 'object' &&
    typeof value.styles === 'object' &&
    typeof value.metadata === 'object'
  )
}

/**
 * Type guard to check if a value is an array of ComponentInstances
 */
export function isComponentInstanceArray(value: any): value is ComponentInstanceArray {
  return Array.isArray(value) && value.every(isComponentInstance)
}

function normalizeSharedId(value: unknown): string | undefined {
  if (typeof value !== 'string') {
    return undefined
  }
  const trimmed = value.trim()
  return trimmed.length > 0 ? trimmed : undefined
}

export function resolveSharedComponentReference(
  instance:
    | Pick<ComponentInstance, 'props'>
    | null
    | undefined
): string | undefined {
  if (!instance) {
    return undefined
  }
  return normalizeSharedId((instance.props as Record<string, unknown> | undefined)?.sharedComponentId)
}
